/*
 * Selling Partner API for FBA Inbound Eligibilty
 *
 * With the FBA Inbound Eligibility API, you can build applications that let sellers get eligibility previews for items before shipping them to Amazon's fulfillment centers. With this API you can find out if an item is eligible for inbound shipment to Amazon's fulfillment centers in a specific marketplace. You can also find out if an item is eligible for using the manufacturer barcode for FBA inventory tracking. Sellers can use this information to inform their decisions about which items to ship Amazon's fulfillment centers.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.fba.eligibility.v1;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing GetItemEligibilityPreviewResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetItemEligibilityPreviewResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetItemEligibilityPreviewResponse
        //private GetItemEligibilityPreviewResponse instance;

        public GetItemEligibilityPreviewResponseTests()
        {
            // TODO uncomment below to create an instance of GetItemEligibilityPreviewResponse
            //instance = new GetItemEligibilityPreviewResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetItemEligibilityPreviewResponse
        /// </summary>
        [Fact]
        public void GetItemEligibilityPreviewResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetItemEligibilityPreviewResponse
            //Assert.IsType<GetItemEligibilityPreviewResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
