/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.fulfillment.inbound.v2024_03_20;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing InboundPlanSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InboundPlanSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InboundPlanSummary
        //private InboundPlanSummary instance;

        public InboundPlanSummaryTests()
        {
            // TODO uncomment below to create an instance of InboundPlanSummary
            //instance = new InboundPlanSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InboundPlanSummary
        /// </summary>
        [Fact]
        public void InboundPlanSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" InboundPlanSummary
            //Assert.IsType<InboundPlanSummary>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'InboundPlanId'
        /// </summary>
        [Fact]
        public void InboundPlanIdTest()
        {
            // TODO unit test for the property 'InboundPlanId'
        }

        /// <summary>
        /// Test the property 'LastUpdatedAt'
        /// </summary>
        [Fact]
        public void LastUpdatedAtTest()
        {
            // TODO unit test for the property 'LastUpdatedAt'
        }

        /// <summary>
        /// Test the property 'MarketplaceIds'
        /// </summary>
        [Fact]
        public void MarketplaceIdsTest()
        {
            // TODO unit test for the property 'MarketplaceIds'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'SourceAddress'
        /// </summary>
        [Fact]
        public void SourceAddressTest()
        {
            // TODO unit test for the property 'SourceAddress'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
