/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.fulfillment.inbound.v2024_03_20;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduleSelfShipAppointmentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleSelfShipAppointmentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduleSelfShipAppointmentResponse
        //private ScheduleSelfShipAppointmentResponse instance;

        public ScheduleSelfShipAppointmentResponseTests()
        {
            // TODO uncomment below to create an instance of ScheduleSelfShipAppointmentResponse
            //instance = new ScheduleSelfShipAppointmentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduleSelfShipAppointmentResponse
        /// </summary>
        [Fact]
        public void ScheduleSelfShipAppointmentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduleSelfShipAppointmentResponse
            //Assert.IsType<ScheduleSelfShipAppointmentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SelfShipAppointmentDetails'
        /// </summary>
        [Fact]
        public void SelfShipAppointmentDetailsTest()
        {
            // TODO unit test for the property 'SelfShipAppointmentDetails'
        }
    }
}
