/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.supplySources.v2020_07_01;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateSupplySourceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSupplySourceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateSupplySourceRequest
        //private UpdateSupplySourceRequest instance;

        public UpdateSupplySourceRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateSupplySourceRequest
            //instance = new UpdateSupplySourceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateSupplySourceRequest
        /// </summary>
        [Fact]
        public void UpdateSupplySourceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateSupplySourceRequest
            //Assert.IsType<UpdateSupplySourceRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }

        /// <summary>
        /// Test the property 'VarConfiguration'
        /// </summary>
        [Fact]
        public void VarConfigurationTest()
        {
            // TODO unit test for the property 'VarConfiguration'
        }

        /// <summary>
        /// Test the property 'Capabilities'
        /// </summary>
        [Fact]
        public void CapabilitiesTest()
        {
            // TODO unit test for the property 'Capabilities'
        }
    }
}
