/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2023-11-15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.datakiosk.v2023_11_15;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing Query
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Query
        //private Query instance;

        public QueryTests()
        {
            // TODO uncomment below to create an instance of Query
            //instance = new Query();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Query
        /// </summary>
        [Fact]
        public void QueryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Query
            //Assert.IsType<Query>(instance);
        }

        /// <summary>
        /// Test the property 'QueryId'
        /// </summary>
        [Fact]
        public void QueryIdTest()
        {
            // TODO unit test for the property 'QueryId'
        }

        /// <summary>
        /// Test the property 'VarQuery'
        /// </summary>
        [Fact]
        public void VarQueryTest()
        {
            // TODO unit test for the property 'VarQuery'
        }

        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Fact]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }

        /// <summary>
        /// Test the property 'ProcessingStatus'
        /// </summary>
        [Fact]
        public void ProcessingStatusTest()
        {
            // TODO unit test for the property 'ProcessingStatus'
        }

        /// <summary>
        /// Test the property 'ProcessingStartTime'
        /// </summary>
        [Fact]
        public void ProcessingStartTimeTest()
        {
            // TODO unit test for the property 'ProcessingStartTime'
        }

        /// <summary>
        /// Test the property 'ProcessingEndTime'
        /// </summary>
        [Fact]
        public void ProcessingEndTimeTest()
        {
            // TODO unit test for the property 'ProcessingEndTime'
        }

        /// <summary>
        /// Test the property 'DataDocumentId'
        /// </summary>
        [Fact]
        public void DataDocumentIdTest()
        {
            // TODO unit test for the property 'DataDocumentId'
        }

        /// <summary>
        /// Test the property 'ErrorDocumentId'
        /// </summary>
        [Fact]
        public void ErrorDocumentIdTest()
        {
            // TODO unit test for the property 'ErrorDocumentId'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
