/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.vendor.df.orders.v2021_12_28;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing OrderAcknowledgementItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderAcknowledgementItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderAcknowledgementItem
        //private OrderAcknowledgementItem instance;

        public OrderAcknowledgementItemTests()
        {
            // TODO uncomment below to create an instance of OrderAcknowledgementItem
            //instance = new OrderAcknowledgementItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderAcknowledgementItem
        /// </summary>
        [Fact]
        public void OrderAcknowledgementItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderAcknowledgementItem
            //Assert.IsType<OrderAcknowledgementItem>(instance);
        }

        /// <summary>
        /// Test the property 'PurchaseOrderNumber'
        /// </summary>
        [Fact]
        public void PurchaseOrderNumberTest()
        {
            // TODO unit test for the property 'PurchaseOrderNumber'
        }

        /// <summary>
        /// Test the property 'VendorOrderNumber'
        /// </summary>
        [Fact]
        public void VendorOrderNumberTest()
        {
            // TODO unit test for the property 'VendorOrderNumber'
        }

        /// <summary>
        /// Test the property 'AcknowledgementDate'
        /// </summary>
        [Fact]
        public void AcknowledgementDateTest()
        {
            // TODO unit test for the property 'AcknowledgementDate'
        }

        /// <summary>
        /// Test the property 'AcknowledgementStatus'
        /// </summary>
        [Fact]
        public void AcknowledgementStatusTest()
        {
            // TODO unit test for the property 'AcknowledgementStatus'
        }

        /// <summary>
        /// Test the property 'SellingParty'
        /// </summary>
        [Fact]
        public void SellingPartyTest()
        {
            // TODO unit test for the property 'SellingParty'
        }

        /// <summary>
        /// Test the property 'ShipFromParty'
        /// </summary>
        [Fact]
        public void ShipFromPartyTest()
        {
            // TODO unit test for the property 'ShipFromParty'
        }

        /// <summary>
        /// Test the property 'ItemAcknowledgements'
        /// </summary>
        [Fact]
        public void ItemAcknowledgementsTest()
        {
            // TODO unit test for the property 'ItemAcknowledgements'
        }
    }
}
