/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.finances.v0;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing ChargeRefundEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChargeRefundEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChargeRefundEvent
        //private ChargeRefundEvent instance;

        public ChargeRefundEventTests()
        {
            // TODO uncomment below to create an instance of ChargeRefundEvent
            //instance = new ChargeRefundEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChargeRefundEvent
        /// </summary>
        [Fact]
        public void ChargeRefundEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChargeRefundEvent
            //Assert.IsType<ChargeRefundEvent>(instance);
        }

        /// <summary>
        /// Test the property 'PostedDate'
        /// </summary>
        [Fact]
        public void PostedDateTest()
        {
            // TODO unit test for the property 'PostedDate'
        }

        /// <summary>
        /// Test the property 'ReasonCode'
        /// </summary>
        [Fact]
        public void ReasonCodeTest()
        {
            // TODO unit test for the property 'ReasonCode'
        }

        /// <summary>
        /// Test the property 'ReasonCodeDescription'
        /// </summary>
        [Fact]
        public void ReasonCodeDescriptionTest()
        {
            // TODO unit test for the property 'ReasonCodeDescription'
        }

        /// <summary>
        /// Test the property 'ChargeRefundTransactions'
        /// </summary>
        [Fact]
        public void ChargeRefundTransactionsTest()
        {
            // TODO unit test for the property 'ChargeRefundTransactions'
        }
    }
}
