/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.merchantFulfillment.v0;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing GetEligibleShipmentServicesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEligibleShipmentServicesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEligibleShipmentServicesRequest
        //private GetEligibleShipmentServicesRequest instance;

        public GetEligibleShipmentServicesRequestTests()
        {
            // TODO uncomment below to create an instance of GetEligibleShipmentServicesRequest
            //instance = new GetEligibleShipmentServicesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEligibleShipmentServicesRequest
        /// </summary>
        [Fact]
        public void GetEligibleShipmentServicesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEligibleShipmentServicesRequest
            //Assert.IsType<GetEligibleShipmentServicesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ShipmentRequestDetails'
        /// </summary>
        [Fact]
        public void ShipmentRequestDetailsTest()
        {
            // TODO unit test for the property 'ShipmentRequestDetails'
        }

        /// <summary>
        /// Test the property 'ShippingOfferingFilter'
        /// </summary>
        [Fact]
        public void ShippingOfferingFilterTest()
        {
            // TODO unit test for the property 'ShippingOfferingFilter'
        }
    }
}
