/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.vendor.shipments.v1;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentMeasurements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentMeasurementsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipmentMeasurements
        //private ShipmentMeasurements instance;

        public ShipmentMeasurementsTests()
        {
            // TODO uncomment below to create an instance of ShipmentMeasurements
            //instance = new ShipmentMeasurements();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentMeasurements
        /// </summary>
        [Fact]
        public void ShipmentMeasurementsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipmentMeasurements
            //Assert.IsType<ShipmentMeasurements>(instance);
        }

        /// <summary>
        /// Test the property 'GrossShipmentWeight'
        /// </summary>
        [Fact]
        public void GrossShipmentWeightTest()
        {
            // TODO unit test for the property 'GrossShipmentWeight'
        }

        /// <summary>
        /// Test the property 'ShipmentVolume'
        /// </summary>
        [Fact]
        public void ShipmentVolumeTest()
        {
            // TODO unit test for the property 'ShipmentVolume'
        }

        /// <summary>
        /// Test the property 'CartonCount'
        /// </summary>
        [Fact]
        public void CartonCountTest()
        {
            // TODO unit test for the property 'CartonCount'
        }

        /// <summary>
        /// Test the property 'PalletCount'
        /// </summary>
        [Fact]
        public void PalletCountTest()
        {
            // TODO unit test for the property 'PalletCount'
        }
    }
}
