/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.shipping.v2;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing TaxDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaxDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaxDetail
        //private TaxDetail instance;

        public TaxDetailTests()
        {
            // TODO uncomment below to create an instance of TaxDetail
            //instance = new TaxDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaxDetail
        /// </summary>
        [Fact]
        public void TaxDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaxDetail
            //Assert.IsType<TaxDetail>(instance);
        }

        /// <summary>
        /// Test the property 'TaxType'
        /// </summary>
        [Fact]
        public void TaxTypeTest()
        {
            // TODO unit test for the property 'TaxType'
        }

        /// <summary>
        /// Test the property 'TaxRegistrationNumber'
        /// </summary>
        [Fact]
        public void TaxRegistrationNumberTest()
        {
            // TODO unit test for the property 'TaxRegistrationNumber'
        }
    }
}
