/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.merchantFulfillment.v0
{
    /// <summary>
    /// An additional set of seller inputs required to purchase shipping.
    /// </summary>
    [DataContract(Name = "AdditionalSellerInputs")]
    public partial class AdditionalSellerInputs : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalSellerInputs" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AdditionalSellerInputs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AdditionalSellerInputs" /> class.
        /// </summary>
        /// <param name="additionalInputFieldName">The name of the additional input field. (required).</param>
        /// <param name="additionalSellerInput">additionalSellerInput (required).</param>
        public AdditionalSellerInputs(string additionalInputFieldName = default(string), AdditionalSellerInput additionalSellerInput = default(AdditionalSellerInput))
        {
            // to ensure "additionalInputFieldName" is required (not null)
            if (additionalInputFieldName == null)
            {
                throw new ArgumentNullException("additionalInputFieldName is a required property for AdditionalSellerInputs and cannot be null");
            }
            this.AdditionalInputFieldName = additionalInputFieldName;
            // to ensure "additionalSellerInput" is required (not null)
            if (additionalSellerInput == null)
            {
                throw new ArgumentNullException("additionalSellerInput is a required property for AdditionalSellerInputs and cannot be null");
            }
            this.AdditionalSellerInput = additionalSellerInput;
        }

        /// <summary>
        /// The name of the additional input field.
        /// </summary>
        /// <value>The name of the additional input field.</value>
        [DataMember(Name = "AdditionalInputFieldName", IsRequired = true, EmitDefaultValue = true)]
        public string AdditionalInputFieldName { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalSellerInput
        /// </summary>
        [DataMember(Name = "AdditionalSellerInput", IsRequired = true, EmitDefaultValue = true)]
        public AdditionalSellerInput AdditionalSellerInput { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdditionalSellerInputs {\n");
            sb.Append("  AdditionalInputFieldName: ").Append(AdditionalInputFieldName).Append("\n");
            sb.Append("  AdditionalSellerInput: ").Append(AdditionalSellerInput).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
