/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.pricing.v0
{
    /// <summary>
    /// Indicates the type of quantity discount this price applies to.
    /// </summary>
    /// <value>Indicates the type of quantity discount this price applies to.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum QuantityDiscountType
    {
        /// <summary>
        /// Enum QUANTITYDISCOUNT for value: QUANTITY_DISCOUNT
        /// </summary>
        [EnumMember(Value = "QUANTITY_DISCOUNT")]
        QUANTITYDISCOUNT = 1
    }

}
