/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.aplusContent.v2020_11_01
{
    /// <summary>
    /// The standard company logo image.
    /// </summary>
    [DataContract(Name = "StandardCompanyLogoModule")]
    public partial class StandardCompanyLogoModule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StandardCompanyLogoModule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StandardCompanyLogoModule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StandardCompanyLogoModule" /> class.
        /// </summary>
        /// <param name="companyLogo">companyLogo (required).</param>
        public StandardCompanyLogoModule(ImageComponent companyLogo = default(ImageComponent))
        {
            // to ensure "companyLogo" is required (not null)
            if (companyLogo == null)
            {
                throw new ArgumentNullException("companyLogo is a required property for StandardCompanyLogoModule and cannot be null");
            }
            this.CompanyLogo = companyLogo;
        }

        /// <summary>
        /// Gets or Sets CompanyLogo
        /// </summary>
        [DataMember(Name = "companyLogo", IsRequired = true, EmitDefaultValue = true)]
        public ImageComponent CompanyLogo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StandardCompanyLogoModule {\n");
            sb.Append("  CompanyLogo: ").Append(CompanyLogo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
