/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.finances.v0
{
    /// <summary>
    /// An item of a debt payment or debt adjustment.
    /// </summary>
    [DataContract(Name = "DebtRecoveryItem")]
    public partial class DebtRecoveryItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DebtRecoveryItem" /> class.
        /// </summary>
        /// <param name="recoveryAmount">recoveryAmount.</param>
        /// <param name="originalAmount">originalAmount.</param>
        /// <param name="groupBeginDate">Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate)..</param>
        /// <param name="groupEndDate">Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate)..</param>
        public DebtRecoveryItem(Currency recoveryAmount = default(Currency), Currency originalAmount = default(Currency), DateTime groupBeginDate = default(DateTime), DateTime groupEndDate = default(DateTime))
        {
            this.RecoveryAmount = recoveryAmount;
            this.OriginalAmount = originalAmount;
            this.GroupBeginDate = groupBeginDate;
            this.GroupEndDate = groupEndDate;
        }

        /// <summary>
        /// Gets or Sets RecoveryAmount
        /// </summary>
        [DataMember(Name = "RecoveryAmount", EmitDefaultValue = false)]
        public Currency RecoveryAmount { get; set; }

        /// <summary>
        /// Gets or Sets OriginalAmount
        /// </summary>
        [DataMember(Name = "OriginalAmount", EmitDefaultValue = false)]
        public Currency OriginalAmount { get; set; }

        /// <summary>
        /// Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate).
        /// </summary>
        /// <value>Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate).</value>
        [DataMember(Name = "GroupBeginDate", EmitDefaultValue = false)]
        public DateTime GroupBeginDate { get; set; }

        /// <summary>
        /// Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate).
        /// </summary>
        /// <value>Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate).</value>
        [DataMember(Name = "GroupEndDate", EmitDefaultValue = false)]
        public DateTime GroupEndDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DebtRecoveryItem {\n");
            sb.Append("  RecoveryAmount: ").Append(RecoveryAmount).Append("\n");
            sb.Append("  OriginalAmount: ").Append(OriginalAmount).Append("\n");
            sb.Append("  GroupBeginDate: ").Append(GroupBeginDate).Append("\n");
            sb.Append("  GroupEndDate: ").Append(GroupEndDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
