/*
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.fba.inventory.v1;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing InventorySummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InventorySummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InventorySummary
        //private InventorySummary instance;

        public InventorySummaryTests()
        {
            // TODO uncomment below to create an instance of InventorySummary
            //instance = new InventorySummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InventorySummary
        /// </summary>
        [Fact]
        public void InventorySummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" InventorySummary
            //Assert.IsType<InventorySummary>(instance);
        }

        /// <summary>
        /// Test the property 'Asin'
        /// </summary>
        [Fact]
        public void AsinTest()
        {
            // TODO unit test for the property 'Asin'
        }

        /// <summary>
        /// Test the property 'FnSku'
        /// </summary>
        [Fact]
        public void FnSkuTest()
        {
            // TODO unit test for the property 'FnSku'
        }

        /// <summary>
        /// Test the property 'SellerSku'
        /// </summary>
        [Fact]
        public void SellerSkuTest()
        {
            // TODO unit test for the property 'SellerSku'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'InventoryDetails'
        /// </summary>
        [Fact]
        public void InventoryDetailsTest()
        {
            // TODO unit test for the property 'InventoryDetails'
        }

        /// <summary>
        /// Test the property 'LastUpdatedTime'
        /// </summary>
        [Fact]
        public void LastUpdatedTimeTest()
        {
            // TODO unit test for the property 'LastUpdatedTime'
        }

        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Fact]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }

        /// <summary>
        /// Test the property 'TotalQuantity'
        /// </summary>
        [Fact]
        public void TotalQuantityTest()
        {
            // TODO unit test for the property 'TotalQuantity'
        }

        /// <summary>
        /// Test the property 'Stores'
        /// </summary>
        [Fact]
        public void StoresTest()
        {
            // TODO unit test for the property 'Stores'
        }
    }
}
