/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.vendor.shipments.v1
{
    /// <summary>
    /// The request schema for the GetShipmentLabels operation.
    /// </summary>
    [DataContract(Name = "TransportationLabels")]
    public partial class TransportationLabels : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransportationLabels" /> class.
        /// </summary>
        /// <param name="pagination">pagination.</param>
        /// <param name="transportLabels">A list of one or more ShipmentLabels..</param>
        public TransportationLabels(Pagination pagination = default(Pagination), List<TransportLabel> transportLabels = default(List<TransportLabel>))
        {
            this.Pagination = pagination;
            this.TransportLabels = transportLabels;
        }

        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>
        [DataMember(Name = "pagination", EmitDefaultValue = false)]
        public Pagination Pagination { get; set; }

        /// <summary>
        /// A list of one or more ShipmentLabels.
        /// </summary>
        /// <value>A list of one or more ShipmentLabels.</value>
        [DataMember(Name = "transportLabels", EmitDefaultValue = false)]
        public List<TransportLabel> TransportLabels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransportationLabels {\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("  TransportLabels: ").Append(TransportLabels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
