/*
 * Selling Partner API for Application Management
 *
 * The Selling Partner API for Application Management lets you programmatically update the client secret on registered applications.
 *
 * The version of the OpenAPI document: 2023-11-30
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;
using Amazon.SellingPartnerAPIAA;

using software.amzn.spapi.Client;
using software.amzn.spapi.Api.applications.v2023_11_30;
using software.amzn.spapi.Model.applications.v2023_11_30;

namespace software.amzn.spapi.Api.applications.v2023_11_30.Test
{
    /// <summary>
    ///  Class for testing ApplicationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ApplicationsApiTests
    {
        private ApplicationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        public void Init()
        {
            // TODO uncomment below to initialize instance for testing
            //instance = new ApplicationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApplicationsApi
        /// </summary>
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ApplicationsApi
            //Assert.IsInstanceOfType(typeof(ApplicationsApi), instance, "instance is a ApplicationsApi");
        }

        
        /// <summary>
        /// Test RotateApplicationClientSecret
        /// </summary>
        [Fact]
        public void RotateApplicationClientSecretTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.RotateApplicationClientSecret();
            
        }
        
    }

}
