name: Test Csharp SDK

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      working-directory: ./csharp/sdk
      run: dotnet restore
    - name: Build
      working-directory: ./csharp/sdk
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./csharp/sdk
      run: dotnet test --no-build --verbosity normal
