/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.pricing.v0;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing SellerFeedbackType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SellerFeedbackTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SellerFeedbackType
        //private SellerFeedbackType instance;

        public SellerFeedbackTypeTests()
        {
            // TODO uncomment below to create an instance of SellerFeedbackType
            //instance = new SellerFeedbackType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SellerFeedbackType
        /// </summary>
        [Fact]
        public void SellerFeedbackTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SellerFeedbackType
            //Assert.IsType<SellerFeedbackType>(instance);
        }

        /// <summary>
        /// Test the property 'SellerPositiveFeedbackRating'
        /// </summary>
        [Fact]
        public void SellerPositiveFeedbackRatingTest()
        {
            // TODO unit test for the property 'SellerPositiveFeedbackRating'
        }

        /// <summary>
        /// Test the property 'FeedbackCount'
        /// </summary>
        [Fact]
        public void FeedbackCountTest()
        {
            // TODO unit test for the property 'FeedbackCount'
        }
    }
}
