/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.aplusContent.v2020_11_01;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing StandardComparisonProductBlock
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StandardComparisonProductBlockTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StandardComparisonProductBlock
        //private StandardComparisonProductBlock instance;

        public StandardComparisonProductBlockTests()
        {
            // TODO uncomment below to create an instance of StandardComparisonProductBlock
            //instance = new StandardComparisonProductBlock();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StandardComparisonProductBlock
        /// </summary>
        [Fact]
        public void StandardComparisonProductBlockInstanceTest()
        {
            // TODO uncomment below to test "IsType" StandardComparisonProductBlock
            //Assert.IsType<StandardComparisonProductBlock>(instance);
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Asin'
        /// </summary>
        [Fact]
        public void AsinTest()
        {
            // TODO unit test for the property 'Asin'
        }

        /// <summary>
        /// Test the property 'Highlight'
        /// </summary>
        [Fact]
        public void HighlightTest()
        {
            // TODO unit test for the property 'Highlight'
        }

        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Fact]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
    }
}
